export const words = [
    "Software",
    "Design",
    "React",
    "Wilfred",
    "Portfolio",
    "Animation",
    "Developer",
    "Technology",
    "NextJS",
    "Hello World",
    "Sass CSS",
    "Git push",
    "Tailwind CSS",
    "HTML5",
    "Javascript",
    "Typescript",
    "APIs",
    "SEO",
    "Python",
    "Software",
    "Design",
    "React",
    "Wilfred",
    "Portfolio",
    "Animation",
    "Developer",
    "Technology",
    "NextJS",
    "Hello World",
    "Sass CSS",
    "Git push",
    "Tailwind CSS",
    "HTML5",
    "Javascript",
    "Typescript",
    "APIs",
    "SEO",
    "Python",
    "Software",
    "Design",
    "React",
    "Wilfred",
    "Portfolio",
    "Animation",
    "Developer",
    "Technology",
    "NextJS",
    "Hello World",
    "Sass CSS",
    "Git push",
    "Tailwind CSS",
    "HTML5",
    "Javascript",
    "Typescript",
    "APIs",
    "SEO",
    "Python",
    "Software",
    "Design",
    "React",
    "Wilfred",
    "Portfolio",
    "Animation",
    "Developer",
    "Technology",
    "NextJS",
    "Hello World",
    "Sass CSS",
    "Git push",
    "Tailwind CSS",
    "HTML5",
    "Javascript",
    "Typescript",
    "APIs",
    "SEO",
    "Python",
    "Software",
    "Design",
    "React",
    "Wilfred",
    "Portfolio",
    "Animation",
    "Developer",
    "Technology",
    "NextJS",
    "Hello World",
    "Sass CSS",
    "Git push",
    "Tailwind CSS",
    "HTML5",
    "Javascript",
    "Typescript",
    "APIs",
    "SEO",
    "Python",
    "Software",
    "Design",
    "React",
    "Wilfred",
    "Portfolio",
    "Animation",
    "Developer",
    "Technology",
    "NextJS",
    "Hello World",
    "Sass CSS",
    "Git push",
    "Tailwind CSS",
    "HTML5",
    "Javascript",
    "Typescript",
    "APIs",
    "SEO",
    "Python",
    "Software",
    "Wilfred",
    "Portfolio",
    "Design",
    "React",
    "Animation",
    "Developer",
    "Technology",
    "NextJS",
    "Hello World",
    "Sass CSS",
    "Git push",
    "Tailwind CSS",
    "HTML5",
    "Javascript",
    "Typescript",
    "APIs",
    "SEO",
    "Python",
];
